### ISSUE TITLE
C#转编的无法兼容呀

### ISSUE THREAD

**Issue by kuangxj** [openctp/openctp#32]
自己用官方给的lib文件转成了C#用的动态链接库，用贵平台的覆盖出错。如图，麻烦提供一个lib文件或其他方式。
![image](https://user-images.githubusercontent.com/46349033/220963981-3e86be3b-2c45-4ec7-bbd3-dcad55deeb15.png)

**Comment by Jedore** [comment]
是否可以提供完整的操作流程，方便理解

**Comment by kuangxj** [comment]
1、通过swig方式，引用CTP官方提供的6.6.1版本的h文件以及两个静态文件（lib），生成了中间件，这里名字叫CTPAdpater.dll。使用CTP官方的肯定没有问题。
2、使用贵平台的覆盖后，出现了中间件无法调用贵平台dll的问题，如上图。

**Comment by Jedore** [comment]
没用过csharp，是不是动态库名称不一致的原因？openctp生成的动态库不是叫CTPAdapter,所以调不到

**Comment by Jedore** [comment]
在c++/python都没有遇到过这种问题，openctp目前没有c#的专业人员，你要不就补充一个重现过程的完整说明（流程及相关文件），也方便去重现及排查分析。
