### ISSUE TITLE
python获取QQ行情时日期解析出错

### ISSUE THREAD

**Issue by congcong009** [openctp/openctp#36]
采用 J 大的 demo 获取 QQ 行情，返回的 A 股数据中，日期解析出错，效果如下：
![@VYA$6Z@)H@BANI}{}YO1HM](https://user-images.githubusercontent.com/2680017/224862870-20038b38-7c20-46e7-8c58-ea34c5e2d721.png)

期望的效果，参考 [API](https://qt.gtimg.cn/q=sh000001,sh600000,hk00700,usAAPL) 的结果
![I@VY{D8GFDHEJLWQG}ZQ1}D](https://user-images.githubusercontent.com/2680017/224862922-32b9b491-f55d-439c-a933-4aa895600b0b.png)

我的运行环境 py3.8，[demo 代码](https://zhuanlan.zhihu.com/p/613699044)

**Comment by Jedore** [comment]
In processing ...

**Comment by congcong009** [comment]
补充信息：pDepthMarketData.ActionDay 可以解析日期，但 pDepthMarketData.TradingDay 解析失效

**Comment by congcong009** [comment]
使用 ctp2QQ/6.6.7_20220304 的dll，问题依旧呢，而且看 thostmduserapi_se.dll 的修改日期为2023-2-24，好像没有更新。是我没找对 dll 吗？

**Comment by congcong009** [comment]
`SZSE 000001 2024-09-04 08:53:30 ActionDay: 20240903 TradingDay: 20240903 UpdateTime: 16:14:54 LastPrice: 10.08
HKEX 00700 2024-09-04 08:53:30 ActionDay: 20240903 TradingDay: 20240903 UpdateTime: 16:08:06 LastPrice: 378.2
SSE 600000 2024-09-04 08:53:30 ActionDay: 20240903 TradingDay: 20240903 UpdateTime: 15:59:04 LastPrice: 8.25
NASD AAPL 2024-09-04 08:53:30 ActionDay: 20240903 TradingDay: 20240903 UpdateTime: 16:00:00 LastPrice: 222.77`

重拉了全部库，dll修改地址时间是2024年8月29日，这个版本对了

另外，主页上好像qq的文件都找不到
![image](https://github.com/user-attachments/assets/577910e3-de86-4c9d-a47f-3c294c1c9a89)
