### ISSUE TITLE
提供沪深交易所股票期权的标的资产信息及标的资产基本行情

### ISSUE THREAD

**Issue by plunixlp** [openctp/openctp#58]
是否可以提供沪深交易所股票期权的标的资产信息及标的资产基本行情

**Comment by krenx1983** [comment]
早就支持了，vip环境可以仿真跟踪，7x24环境可以调试程序。
https://mp.weixin.qq.com/s?__biz=Mzk0ODI0NDE2Ng==&mid=2247485356&idx=1&sn=2555d4904fb3b4a47a023dea304d0ea6&chksm=c36bdc05f41c5513d60a61fcf007d905a1abecc52490e354ea4765249a0fd953d392a70ba2bc&token=2114132773&lang=zh_CN#rd

**Comment by plunixlp** [comment]
比如 tcp://121.37.80.177:20002 里查询OnRspQryInstrument得到了SZSE个股期权90003175的信息，但是没有标的资产的159901的信息。
![image](https://github.com/user-attachments/assets/96ece01d-a3f0-4783-9725-5683ffbcf848)
 而在tcp://121.37.90.193:20002里查询OnRspQryInstrument得到的是UnderlyingInstrID 为空。

**Comment by krenx1983** [comment]
vip环境合约最全，500/年

**Comment by plunixlp** [comment]
> vip环境合约最全，500/年

VIP环境包含了沪深ETF标的资产的信息和基本行情吗？
